-- 来源: 1131_file_1131.txt
-- SQL 数量: 13

SELECT 2 BETWEEN 1 AND 3 AS RESULT ;

SELECT 2 >= 1 AND 2 <= 3 AS RESULT ;

SELECT 2 NOT BETWEEN 1 AND 3 AS RESULT ;

SELECT 2 < 1 OR 2 > 3 AS RESULT ;

SELECT 2 + 2 IS NULL AS RESULT ;

SELECT 2 + 2 IS NOT NULL AS RESULT ;

SELECT 2 + 2 ISNULL AS RESULT ;

SELECT 2 + 2 NOTNULL AS RESULT ;

SELECT 2 + 2 IS DISTINCT FROM NULL AS RESULT ;

SELECT 2 + 2 IS NOT DISTINCT FROM NULL AS RESULT ;

select 1 <=> 1 AS RESULT ;

select NULL <=> 1 AS RESULT ;

select NULL <=> NULL AS RESULT ;

