-- 来源: 1185_ALTER APP WORKLOAD GROUP MAPPING.txt
-- SQL 数量: 7

CREATE RESOURCE POOL pool1 WITH ( CONTROL_GROUP = "High" );

CREATE WORKLOAD GROUP wg_hr1 USING RESOURCE POOL pool1 ;

CREATE APP WORKLOAD GROUP MAPPING app_wg_map1 ;

ALTER APP WORKLOAD GROUP MAPPING app_wg_map1 WITH ( WORKLOAD_GPNAME = wg_hr1 );

DROP APP WORKLOAD GROUP MAPPING app_wg_map1 ;

DROP WORKLOAD GROUP wg_hr1 ;

DROP RESOURCE POOL pool1 ;

