-- 来源: 1206_ALTER RESOURCE POOL.txt
-- SQL 数量: 6

CREATE RESOURCE POOL pool1 ;

ALTER RESOURCE POOL pool1 WITH ( CONTROL_GROUP = "High" );

ALTER RESOURCE POOL pool1 WITH ( CONTROL_GROUP = "class1:Low" );

ALTER RESOURCE POOL pool1 WITH ( CONTROL_GROUP = "class1:wg1" );

ALTER RESOURCE POOL pool1 WITH ( CONTROL_GROUP = "class1:wg2:3" );

DROP RESOURCE POOL pool1 ;

