-- 来源: 1212_ALTER SESSION.txt
-- SQL 数量: 15

CREATE SCHEMA ds ;

SET SEARCH_PATH TO ds , public ;

SET DATESTYLE TO postgres , dmy ;

ALTER SESSION SET NAMES 'UTF8' ;

SET TIME ZONE 'PST8PDT' ;

SET TIME ZONE 'Europe/Rome' ;

ALTER SESSION SET CURRENT_SCHEMA TO tpcds ;

ALTER SESSION SET XML OPTION DOCUMENT ;

CREATE ROLE joe WITH PASSWORD '********' ;

ALTER SESSION SET SESSION AUTHORIZATION joe PASSWORD '********' ;

DROP SCHEMA ds ;

DROP ROLE joe ;

START TRANSACTION ;

ALTER SESSION SET TRANSACTION READ ONLY ;

END ;

