-- 来源: 1224_ALTER WORKLOAD GROUP.txt
-- SQL 数量: 5

CREATE RESOURCE POOL pool1 ;

CREATE WORKLOAD GROUP group1 ;

ALTER WORKLOAD GROUP group1 USING RESOURCE POOL pool1 WITH ( ACT_STATEMENTS = 10 );

DROP WORKLOAD GROUP group1 ;

DROP RESOURCE POOL pool1 ;

