-- 来源: 1225_ANALYZE _ ANALYSE.txt
-- SQL 数量: 6

CREATE TABLE customer_info ( WR_RETURNED_DATE_SK INTEGER , WR_RETURNED_TIME_SK INTEGER , WR_ITEM_SK INTEGER NOT NULL , WR_REFUNDED_CUSTOMER_SK INTEGER ) DISTRIBUTE BY HASH ( WR_ITEM_SK );

CREATE TABLE customer_par ( WR_RETURNED_DATE_SK INTEGER , WR_RETURNED_TIME_SK INTEGER , WR_ITEM_SK INTEGER NOT NULL , WR_REFUNDED_CUSTOMER_SK INTEGER ) DISTRIBUTE BY HASH ( WR_ITEM_SK ) PARTITION BY RANGE ( WR_RETURNED_DATE_SK ) ( PARTITION P1 VALUES LESS THAN ( 2452275 ), PARTITION P2 VALUES LESS THAN ( 2452640 ), PARTITION P3 VALUES LESS THAN ( 2453000 ), PARTITION P4 VALUES LESS THAN ( MAXVALUE ) ) ENABLE ROW MOVEMENT ;

ANALYZE customer_info ;

ANALYZE VERBOSE customer_info ;

DROP TABLE customer_info ;

DROP TABLE customer_par ;

