-- 来源: 1238_CREATE APP WORKLOAD GROUP MAPPING.txt
-- SQL 数量: 8

CREATE RESOURCE POOL pool1 WITH ( CONTROL_GROUP = "High" );

CREATE WORKLOAD GROUP group1 USING RESOURCE POOL pool1 ;

CREATE APP WORKLOAD GROUP MAPPING app_wg_map1 WITH ( WORKLOAD_GPNAME = group1 );

CREATE APP WORKLOAD GROUP MAPPING app_wg_map2 ;

DROP APP WORKLOAD GROUP MAPPING app_wg_map1 ;

DROP APP WORKLOAD GROUP MAPPING app_wg_map2 ;

DROP WORKLOAD GROUP group1 ;

DROP RESOURCE POOL pool1 ;

