-- 来源: 1274_CREATE TEXT SEARCH CONFIGURATION.txt
-- SQL 数量: 12

CREATE TEXT SEARCH CONFIGURATION ngram2 ( parser = ngram ) WITH ( gram_size = 2 , grapsymbol_ignore = false );

CREATE TEXT SEARCH CONFIGURATION ngram3 ( copy = ngram2 ) WITH ( gram_size = 2 , grapsymbol_ignore = false );

ALTER TEXT SEARCH CONFIGURATION ngram2 ADD MAPPING FOR multisymbol WITH simple ;

CREATE USER joe IDENTIFIED BY '********' ;

ALTER TEXT SEARCH CONFIGURATION ngram2 OWNER TO joe ;

ALTER TEXT SEARCH CONFIGURATION ngram2 SET SCHEMA joe ;

ALTER TEXT SEARCH CONFIGURATION joe . ngram2 RENAME TO ngram_2 ;

ALTER TEXT SEARCH CONFIGURATION joe . ngram_2 DROP MAPPING IF EXISTS FOR multisymbol ;

DROP TEXT SEARCH CONFIGURATION joe . ngram_2 ;

DROP TEXT SEARCH CONFIGURATION ngram3 ;

DROP SCHEMA IF EXISTS joe CASCADE ;

DROP ROLE IF EXISTS joe ;

