-- 来源: 1280_CREATE WORKLOAD GROUP.txt
-- SQL 数量: 8

CREATE WORKLOAD GROUP wg_name1 ;

CREATE RESOURCE POOL pool1 ;

CREATE WORKLOAD GROUP wg_name2 USING RESOURCE POOL pool1 ;

CREATE WORKLOAD GROUP wg_name3 USING RESOURCE POOL pool1 WITH ( ACT_STATEMENTS = 10 );

DROP WORKLOAD GROUP wg_name1 ;

DROP WORKLOAD GROUP wg_name2 ;

DROP WORKLOAD GROUP wg_name3 ;

DROP RESOURCE POOL pool1 ;

