-- 来源: 1452_file_1452.txt
-- SQL 数量: 56

DROP TABLE IF EXISTS EXAMPLE1;

CREATE TABLE EXAMPLE1(COL1 INT);

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE() AS BEGIN FOR i IN 0..20 LOOP INSERT INTO EXAMPLE1(COL1) VALUES (i);

call TRANSACTION_EXAMPLE();

CREATE OR REPLACE PROCEDURE TEST_COMMIT_INSERT_EXCEPTION_ROLLBACK() AS BEGIN DROP TABLE IF EXISTS TEST_COMMIT;

call TEST_COMMIT_INSERT_EXCEPTION_ROLLBACK();

BEGIN;

CREATE OR REPLACE PROCEDURE TEST_COMMIT2() IS BEGIN DROP TABLE IF EXISTS TEST_COMMIT;

call TEST_COMMIT2();

SHOW explain_perf_mode;

SHOW enable_force_vector_engine;

CREATE OR REPLACE PROCEDURE GUC_ROLLBACK() AS BEGIN SET enable_force_vector_engine = on;

call GUC_ROLLBACK();

SHOW explain_perf_mode;

SHOW enable_force_vector_engine;

SET enable_force_vector_engine = off;

CREATE OR REPLACE PROCEDURE STP_SAVEPOINT_EXAMPLE1() AS BEGIN INSERT INTO EXAMPLE1 VALUES(1);

call STP_SAVEPOINT_EXAMPLE1();

CREATE OR REPLACE PROCEDURE STP_SAVEPOINT_EXAMPLE2() AS BEGIN INSERT INTO EXAMPLE1 VALUES(2);

BEGIN;

CALL STP_SAVEPOINT_EXAMPLE2();

SELECT * FROM EXAMPLE1;

COMMIT;

CREATE OR REPLACE PROCEDURE STP_SAVEPOINT_EXAMPLE3() AS BEGIN INSERT INTO EXAMPLE1 VALUES(1);

BEGIN;

INSERT INTO EXAMPLE1 VALUES(3);

CALL STP_SAVEPOINT_EXAMPLE3();

ROLLBACK TO SAVEPOINT s1;

SELECT * FROM EXAMPLE1;

COMMIT;

CREATE OR REPLACE FUNCTION FUNCTION_EXAMPLE1() RETURN INT AS EXP INT;

call FUNCTION_EXAMPLE1();

CREATE OR REPLACE FUNCTION FUNCTION_TRI_EXAMPLE2() RETURN TRIGGER AS EXP INT;

CREATE TRIGGER TRIGGER_EXAMPLE AFTER DELETE ON EXAMPLE1 FOR EACH ROW EXECUTE PROCEDURE FUNCTION_TRI_EXAMPLE2();

DELETE FROM EXAMPLE1;

DROP TABLE IF EXISTS EXAMPLE1;

CREATE TABLE EXAMPLE1(COL1 INT);

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE1() IMMUTABLE AS EXP INT;

CALL TRANSACTION_EXAMPLE1();

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE2(EXP_OUT OUT INT) AS EXP INT;

CALL TRANSACTION_EXAMPLE2(100);

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE3() AS BEGIN FOR i IN 0..20 LOOP INSERT INTO EXAMPLE1 (col1) VALUES (i);

CALL TRANSACTION_EXAMPLE3();

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE4() SET ARRAY_NULLS TO "ON" AS BEGIN FOR i IN 0..20 LOOP INSERT INTO EXAMPLE1 (col1) VALUES (i);

CALL TRANSACTION_EXAMPLE4();

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE5(INTIN IN INT, INTOUT OUT INT) AS BEGIN INTOUT := INTIN + 1;

CREATE OR REPLACE PROCEDURE TRANSACTION_EXAMPLE6() AS CURSOR CURSOR1(EXPIN INT) IS SELECT TRANSACTION_EXAMPLE5(EXPIN);

CALL TRANSACTION_EXAMPLE6();

CREATE OR REPLACE PROCEDURE exec_func1() AS BEGIN CREATE TABLE TEST_exec(A INT);

CREATE OR REPLACE PROCEDURE exec_func2() AS BEGIN EXECUTE exec_func1();

CALL exec_func2();

CREATE OR REPLACE PROCEDURE exec_func3(RET_NUM OUT INT) AS BEGIN RET_NUM := 1+1;

CREATE OR REPLACE PROCEDURE exec_func4(ADD_NUM IN INT) AS SUM_NUM INT;

CALL exec_func4(1);

CREATE OR REPLACE PROCEDURE STP_SAVEPOINT_EXAMPLE3() AS BEGIN INSERT INTO EXAMPLE1 VALUES(2);

BEGIN;

