-- 来源: 1490_file_1490.txt
-- SQL 数量: 8

CREATE TABLE t2(a INT, b INT);

INSERT INTO t2 VALUES(1,2);

SELECT * FROM t2;

CREATE OR REPLACE PROCEDURE autonomous_4(a INT, b INT) AS DECLARE num3 INT := a;

CREATE OR REPLACE PROCEDURE autonomous_5(a INT, b INT) AS DECLARE BEGIN DBE_OUTPUT.PRINT_LINE('JUST NO USE CALL.');

SELECT autonomous_5(11,22);

SELECT * FROM t2 ORDER BY a;

DROP TABLE t2;

