-- 来源: 1492_file_1492.txt
-- SQL 数量: 6

CREATE TABLE t4(a INT, b INT, c TEXT);

CREATE OR REPLACE FUNCTION autonomous_32(a INT ,b INT ,c TEXT) RETURN INT AS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE FUNCTION autonomous_33(num1 INT) RETURN INT AS DECLARE num3 INT := 220;

SELECT autonomous_33(0);

SELECT * FROM t4;

DROP TABLE t4;

