-- 来源: 3133_file_3133.txt
-- SQL 数量: 12

CREATE OR REPLACE PROCEDURE table_proc AS DECLARE TYPE TABLE_INTEGER IS TABLE OF INTEGER ;

CALL table_proc ();

DROP PROCEDURE table_proc ;

CREATE OR REPLACE PROCEDURE nest_table_proc AS DECLARE TYPE TABLE_INTEGER IS TABLE OF INTEGER ;

CALL nest_table_proc ();

DROP PROCEDURE nest_table_proc ;

CREATE OR REPLACE PROCEDURE index_table_proc AS DECLARE TYPE TABLE_INTEGER IS TABLE OF INTEGER INDEX BY INTEGER ;

CALL index_table_proc ();

DROP PROCEDURE index_table_proc ;

CREATE OR REPLACE PROCEDURE nest_table_proc AS DECLARE TYPE TABLE_INTEGER IS TABLE OF INTEGER INDEX BY INTEGER ;

CALL nest_table_proc ();

DROP PROCEDURE nest_table_proc ;

