-- 来源: 3202_file_3202.txt
-- SQL 数量: 50

CREATE TABLE test_trigger_des_tbl(id1 int, id2 int, id3 int);

CREATE OR REPLACE FUNCTION tri_insert_func() RETURNS TRIGGER AS $$ DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

DROP TABLE test_trigger_des_tbl;

CREATE TABLE t1(a INT ,b TEXT);

DECLARE

SELECT * FROM t1;

DROP TABLE t1;

CREATE TABLE sections(section_id INT);

INSERT INTO sections VALUES(1);

INSERT INTO sections VALUES(1);

INSERT INTO sections VALUES(1);

INSERT INTO sections VALUES(1);

CREATE OR REPLACE PROCEDURE proc_sys_ref(OUT c1 REFCURSOR) IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE proc_sys_call() AS DECLARE c1 SYS_REFCURSOR;

CALL proc_sys_call();

DROP PROCEDURE proc_sys_ref;

DROP PROCEDURE proc_sys_call;

CREATE OR REPLACE PROCEDURE proc_sys_ref(IN c1 REFCURSOR) IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE proc_sys_call() AS DECLARE c1 SYS_REFCURSOR;

CALL proc_sys_call();

DROP PROCEDURE proc_sys_ref;

DROP PROCEDURE IF EXISTS proc_sys_ref;

CREATE OR REPLACE FUNCTION proc_sys_ref() RETURN SYS_REFCURSOR IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

DROP FUNCTION IF EXISTS proc_sys_ref;

CREATE OR REPLACE FUNCTION proc_sys_ref(C1 out SYS_REFCURSOR) return SYS_REFCURSOR IS gaussdb$# declare gaussdb$# PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE proc_sys_ref(OUT c1 REFCURSOR) IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

begin;

call proc_sys_ref(null);

fetch "<unnamed portal 1>";

DROP PROCEDURE proc_sys_ref;

DROP TABLE sections;

CREATE TABLE test_in (id INT,a DATE);

CREATE OR REPLACE FUNCTION autonomous_out() RETURNS RECORD LANGUAGE PLPGSQL AS $$ DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

SELECT ok.id,ok.a FROM autonomous_out() AS ok(id INT,a DATE);

CREATE TYPE rec IS (e1 INTEGER, e2 VARCHAR2);

CREATE OR REPLACE FUNCTION func(ele3 INOUT VARCHAR2) RETURN rec AS i INTEGER;

CALL func(1);

DROP TABLE test_in;

DROP FUNCTION autonomous_out;

DROP FUNCTION func;

CREATE OR REPLACE PROCEDURE auto_func(r INT) AS DECLARE a INT;

call auto_func(1);

DROP FUNCTION auto_func;

CREATE TABLE test_in (id INT,a DATE);

CREATE TABLE test_main (id INT,a DATE);

INSERT INTO test_main VALUES (1111,'2021-01-01'),(2222,'2021-02-02');

TRUNCATE test_in,test_main;

CREATE OR REPLACE FUNCTION autonomous_f_022(num1 INT) RETURNS SETOF test_in LANGUAGE PLPGSQL AS $$ DECLARE count INT :=3;

DROP TABLE test_main;

DROP TABLE test_in;

