-- 来源: 3205_file_3205.txt
-- SQL 数量: 8

CREATE TABLE t4(a INT, b INT, c TEXT);

CREATE OR REPLACE FUNCTION autonomous_32(a INT ,b INT ,c TEXT) RETURN INT AS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE FUNCTION autonomous_33(num1 INT) RETURN INT AS DECLARE num3 INT := 220;

SELECT autonomous_33(0);

SELECT * FROM t4;

DROP TABLE t4;

DROP FUNCTION autonomous_32;

DROP FUNCTION autonomous_32;

