-- 来源: 4318_PBE.txt
-- SQL 数量: 14

PREPARE p1(int) AS SELECT * FROM t1 WHERE c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p1(1);

PREPARE p2(INT, INT) AS SELECT * FROM t1 WHERE c1 = $1 AND c2 = $2;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p2(1, 2);

set plan_cache_mode = 'force_generic_plan';

PREPARE p3(TEXT) AS SELECT * FROM t1 WHERE c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p3('12');

PREPARE p4(INT) AS SELECT * FROM t1 WHERE c1 = ALL(SELECT c2 FROM t1 WHERE c1 > $1);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p4(1);

PREPARE p5(name) AS SELECT * FROM t1 WHERE c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p5('12');

create sequence seq;

PREPARE p6(TEXT) AS SELECT * FROM t1 WHERE c1 = currval($1);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p6('seq');

