-- 来源: 4409_TIPS.txt
-- SQL 数量: 41

DROP TABLE IF EXISTS ILM_TABLE;

CREATE TABLE ILM_TABLE(a int);

ALTER TABLE ILM_TABLE ILM ADD POLICY ROW STORE COMPRESS ADVANCED ROW AFTER 3 MONTHS OF NO MODIFICATION;

SELECT * FROM gs_adm_ilmresults ORDER BY task_id desc;

DBE_ILM.STOP_ILM (task_id => V_TASK, p_drop_running_Jobs => FALSE, p_Jobname => V_JOBNAME);

DROP TABLE IF EXISTS ILM_TABLE;

CREATE TABLE ILM_TABLE(a int);

ALTER TABLE ILM_TABLE ILM ADD POLICY ROW STORE COMPRESS ADVANCED ROW AFTER 3 MONTHS OF NO MODIFICATION;

CALL DBE_ILM_ADMIN.DISABLE_ILM();

CALL DBE_ILM_ADMIN.ENABLE_ILM();

CALL DBE_ILM_ADMIN.CUSTOMIZE_ILM(11, 1);

CALL DBE_ILM_ADMIN.CUSTOMIZE_ILM(12, 10);

CALL DBE_ILM_ADMIN.CUSTOMIZE_ILM(1, 1);

CALL DBE_ILM_ADMIN.CUSTOMIZE_ILM(13, 512);

DBE_COMPRESSION.GET_COMPRESSION_RATIO ( scratchtbsname IN VARCHAR2, ownname IN VARCHAR2, objname IN VARCHAR2, subobjname IN VARCHAR2, comptype IN NUMBER, blkcnt_cmp OUT PLS_INTEGER, blkcnt_uncmp OUT PLS_INTEGER, row_cmp OUT PLS_INTEGER, row_uncmp OUT PLS_INTEGER, cmp_ratio OUT NUMBER, comptype_str OUT VARCHAR2, sample_ratio IN INTEGER DEFAULT 20, objtype IN PLS_INTEGER DEFAULT OBJTYPE_TABLE);

ALTER DATABASE set ilm = on ;

CREATE user user1 IDENTIFIED BY '********' ;

CREATE user user2 IDENTIFIED BY '********' ;

SET ROLE user1 PASSWORD '********' ;

CREATE TABLE TEST_DATA ( ORDER_ID INT , GOODS_NAME TEXT , CREATE_TIME TIMESTAMP ) ILM ADD POLICY ROW STORE COMPRESS ADVANCED ROW AFTER 1 DAYS OF NO MODIFICATION ;

DBE_HEAT_MAP.ROW_HEAT_MAP( owner IN VARCHAR2, segment_name IN VARCHAR2, partition_name IN VARCHAR2 DEFAULT NULL, ctid IN VARCHAR2,);

ALTER DATABASE set ilm = on ;

CREATE Schema HEAT_MAP_DATA ;

SET current_schema = HEAT_MAP_DATA ;

CREATE TABLESPACE example1 RELATIVE LOCATION 'tablespace1' ;

CREATE TABLE HEAT_MAP_DATA . heat_map_table ( id INT , value TEXT ) TABLESPACE example1 ;

INSERT INTO HEAT_MAP_DATA . heat_map_table VALUES ( 1 , 'test_data_row_1' );

SELECT * from DBE_HEAT_MAP . ROW_HEAT_MAP ( owner => 'heat_map_data' , segment_name => 'heat_map_table' , partition_name => NULL , ctid => '(0,1)' );

SELECT * FROM GS_ADM_ILMPARAMETERS;

SELECT * FROM GS_ADM_ILMPOLICIES;

SELECT * FROM GS_MY_ILMPOLICIES;

SELECT * FROM GS_ADM_ILMDATAMOVEMENTPOLICIES;

SELECT * FROM GS_MY_ILMDATAMOVEMENTPOLICIES;

SELECT * FROM GS_ADM_ILMOBJECTS;

SELECT * FROM GS_MY_ILMOBJECTS;

SELECT * FROM GS_ADM_ILMTASKS;

SELECT * FROM GS_MY_ILMTASKS;

SELECT * FROM GS_ADM_ILMEVALUATIONDETAILS;

SELECT * FROM GS_MY_ILMEVALUATIONDETAILS;

SELECT * FROM GS_ADM_ILMRESULTS;

SELECT * FROM GS_MY_ILMRESULTS;

