-- 来源: 1191_ALTER DEFAULT PRIVILEGES.txt
-- SQL 数量: 10

CREATE SCHEMA tpcds ;

ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds GRANT SELECT ON TABLES TO PUBLIC ;

CREATE USER jack PASSWORD '******' ;

ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds GRANT INSERT ON TABLES TO jack ;

GRANT USAGE , CREATE ON SCHEMA tpcds TO jack ;

ALTER DEFAULT PRIVILEGES FOR ROLE jack IN SCHEMA tpcds GRANT INSERT ON TABLES TO jack ;

ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds REVOKE SELECT ON TABLES FROM PUBLIC ;

ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds REVOKE INSERT ON TABLES FROM jack ;

DROP USER jack ;

DROP SCHEMA tpcds CASCADE ;

