-- 来源: 1470_DBE_ILM.txt
-- SQL 数量: 10

CREATE DATABASE ilmtabledb with dbcompatibility = 'ORA' ;

\ c ilmtabledb

ALTER DATABASE set ilm = on ;

CREATE Schema ILM_DATA ;

SET current_schema = ILM_DATA ;

CREATE SEQUENCE ILM_DATA . ORDER_TABLE_SE_ORDER_ID MINVALUE 1 ;

CREATE OR REPLACE PROCEDURE ILM_DATA . ORDER_TABLE_CREATE_DATA ( NUM INTEGER ) IS BEGIN FOR X IN 1 .. NUM LOOP INSERT INTO ORDER_TABLE VALUES ( ORDER_TABLE_SE_ORDER_ID . nextval , '零食大礼包A' , NOW ());

CREATE TABLE ILM_DATA . ORDER_TABLE ( ORDER_ID INT , GOODS_NAME TEXT , CREATE_TIME TIMESTAMP ) WITH ( STORAGE_TYPE = ASTORE ) ILM ADD POLICY ROW STORE COMPRESS ADVANCED ROW AFTER 1 DAYS OF NO MODIFICATION ;

EXECUTE DIRECT ON DATANODES 'SELECT A.DBNAME, A.JOB_STATUS, A.ENABLE, A.FAILURE_MSG FROM PG_JOB A WHERE A.DBNAME = ''ilmtabledb'' AND A.JOB_NAME LIKE ''ilmjob$_%'' ORDER BY A.JOB_NAME DESC LIMIT 1' ;

CALL DBE_ILM . STOP_ILM ( - 1 , true , NULL );

