-- 来源: 1489_file_1489.txt
-- SQL 数量: 42

CREATE TABLE test_trigger_des_tbl(id1 int, id2 int, id3 int);

CREATE OR REPLACE FUNCTION tri_insert_func() RETURNS TRIGGER AS $$ DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

DROP TABLE test_trigger_des_tbl;

CREATE TABLE t1(a INT ,b TEXT);

DECLARE

SELECT * FROM t1;

DROP TABLE t1;

CREATE TABLE sections(section_id INT);

INSERT INTO sections VALUES(1);

INSERT INTO sections VALUES(1);

INSERT INTO sections VALUES(1);

INSERT INTO sections VALUES(1);

CREATE OR REPLACE PROCEDURE proc_sys_ref(OUT c1 REFCURSOR) IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE proc_sys_call() AS DECLARE c1 SYS_REFCURSOR;

CALL proc_sys_call();

CREATE OR REPLACE PROCEDURE proc_sys_ref(IN c1 REFCURSOR) IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE proc_sys_call() AS DECLARE c1 SYS_REFCURSOR;

CALL proc_sys_call();

DROP PROCEDURE IF EXISTS proc_sys_ref;

CREATE OR REPLACE function proc_sys_ref() RETURN SYS_REFCURSOR IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE FUNCTION proc_sys_ref(c1 OUT SYS_REFCURSOR) RETURN SYS_REFCURSOR IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE proc_sys_ref(OUT c1 REFCURSOR) IS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

begin;

call proc_sys_ref(null);

fetch "<unnamed portal 1>";

DROP PROCEDURE proc_sys_ref;

DROP TABLE sections;

CREATE OR REPLACE PROCEDURE autonomous_test_in_p_116(num1 INT ) IMMUTABLE AS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE OR REPLACE PROCEDURE autonomous_test_in_p_117(num1 INT ) STABLE AS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CREATE TABLE test_lock (id INT,a DATE);

INSERT INTO test_lock VALUES (10,SYSDATE),(11,SYSDATE),(12,SYSDATE);

CREATE OR REPLACE FUNCTION autonomous_test_lock(num1 INT,num2 INT) RETURNS INTEGER LANGUAGE plpgsql AS $$ DECLARE num3 INT := 4;

START TRANSACTION;

UPDATE test_lock SET a=SYSDATE WHERE id =11;

CALL autonomous_test_lock(1,1);

DROP TABLE test_lock;

CREATE OR REPLACE FUNCTION auto_func() RETURN RECORD AS DECLARE TYPE rec_type IS RECORD(c1 INT, c2 INT);

SELECT auto_func();

CREATE OR REPLACE PROCEDURE auto_func(r INT) AS DECLARE a INT;

call auto_func(1);

CREATE OR REPLACE FUNCTION test_set() RETURN SETOF INT AS DECLARE PRAGMA AUTONOMOUS_TRANSACTION;

CALL test_set();

