-- 来源: 2888_ALTER DEFAULT PRIVILEGES.txt
-- SQL 数量: 10

CREATE SCHEMA tpcds;

--将创建在模式tpcds里的所有表（和视图）的SELECT权限授予每一个用户。
ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds GRANT SELECT ON TABLES TO PUBLIC;

--创建用户普通用户jack。
CREATE USER jack PASSWORD ' ******** ';

--将tpcds下的所有表的插入权限授予用户jack。
ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds GRANT INSERT ON TABLES TO jack;

--将tpcds下由jack创建的所有表的插入权限授予用户jack。
GRANT USAGE,CREATE ON SCHEMA tpcds TO jack;

ALTER DEFAULT PRIVILEGES FOR ROLE jack IN SCHEMA tpcds GRANT INSERT ON TABLES TO jack;

--撤销上述权限。
ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds REVOKE SELECT ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA tpcds REVOKE INSERT ON TABLES FROM jack;

--删除用户jack。
DROP USER jack CASCADE;

--删除SCHEMA。
DROP SCHEMA tpcds;

