-- 来源: 2966_CREATE RESOURCE POOL.txt
-- SQL 数量: 10

CREATE RESOURCE POOL pool1 ;

CREATE RESOURCE POOL pool2 WITH ( CONTROL_GROUP = "High" );

CREATE RESOURCE POOL pool3 WITH ( CONTROL_GROUP = "class1:Low" );

CREATE RESOURCE POOL pool4 WITH ( CONTROL_GROUP = "class1:wg1" );

CREATE RESOURCE POOL pool5 WITH ( CONTROL_GROUP = "class1:wg2:3" );

DROP RESOURCE POOL pool1 ;

DROP RESOURCE POOL pool2 ;

DROP RESOURCE POOL pool3 ;

DROP RESOURCE POOL pool4 ;

DROP RESOURCE POOL pool5 ;

