-- 来源: 3178_DBE_COMPRESSION.txt
-- SQL 数量: 6

alter database set ilm = on ;

CREATE user user1 IDENTIFIED BY 'Gauss_zzy123' ;

CREATE user user2 IDENTIFIED BY 'Gauss_zzy123' ;

SET ROLE user1 PASSWORD 'Gauss_zzy123' ;

CREATE TABLE TEST_DATA ( ORDER_ID INT , GOODS_NAME TEXT , CREATE_TIME TIMESTAMP ) ILM ADD POLICY ROW STORE COMPRESS ADVANCED ROW AFTER 1 DAYS OF NO MODIFICATION ;

SELECT DBE_COMPRESSION . GET_COMPRESSION_TYPE ( 'user1' , 'test_data' , '(0,1)' , NULL );

