-- 来源: 3181_DBE_ILM.txt
-- SQL 数量: 10

ALTER DATABASE set ilm = on ;

CREATE Schema ILM_DATA ;

SET current_schema = ILM_DATA ;

CREATE SEQUENCE ILM_DATA . ORDER_TABLE_SE_ORDER_ID MINVALUE 1 ;

CREATE OR REPLACE PROCEDURE ILM_DATA . ORDER_TABLE_CREATE_DATA ( NUM INTEGER ) IS BEGIN FOR X IN 1 .. NUM LOOP INSERT INTO ORDER_TABLE VALUES ( ORDER_TABLE_SE_ORDER_ID . nextval , '零食大礼包A' , NOW ());

CREATE TABLE ILM_DATA . ORDER_TABLE ( ORDER_ID INT , GOODS_NAME TEXT , CREATE_TIME TIMESTAMP ) WITH ( STORAGE_TYPE = ASTORE ) ILM ADD POLICY ROW STORE COMPRESS ADVANCED ROW AFTER 1 DAYS OF NO MODIFICATION ;

SELECT ORDER_ID , DBE_COMPRESSION . GET_COMPRESSION_TYPE ( 'ilm_data' , 'order_table' , ctid :: text , NULL ) FROM ILM_DATA . ORDER_TABLE ;

SELECT ORDER_ID , DBE_HEAT_MAP . ROW_HEAT_MAP ( 'ilm_data' , 'order_table' , NULL , ctid :: text ) FROM ILM_DATA . ORDER_TABLE ;

SELECT ORDER_ID , DBE_COMPRESSION . GET_COMPRESSION_TYPE ( 'ilm_data' , 'order_table' , ctid :: text , NULL ) FROM ILM_DATA . ORDER_TABLE ;

CALL DBE_ILM . STOP_ILM ( - 1 , true , NULL );

