-- 来源: 4548_PBE.txt
-- SQL 数量: 35

--设置参数
set plan_cache_mode = 'force_generic_plan';

PREPARE p1(int) AS SELECT * FROM t1 WHERE c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p1(1);

PREPARE p2(int) AS SELECT * FROM t1 WHERE c1 < $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p2(1);

PREPARE p3(int) AS SELECT * FROM t1 WHERE c1 > $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p3(1);

PREPARE p5(INT, INT) AS SELECT * FROM t1 WHERE c1 = $1 AND c2 = $2;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p5(1, 2);

PREPARE p6(INT, INT) AS SELECT * FROM t1 WHERE c1 = $1 OR c2 = $2;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p6(1, 2);

PREPARE p7(INT) AS SELECT * FROM t1 WHERE NOT c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) execute p7(1);

PREPARE p8(INT, INT, INT) AS SELECT * FROM t1 WHERE c1 IN ($1, $2, $3);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p8(1, 2, 3);

PREPARE p9(INT, INT, INT) AS SELECT * FROM t1 WHERE c1 NOT IN ($1, $2, $3);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p9(1, 2, 3);

PREPARE p10(INT, INT, INT) AS SELECT * FROM t1 WHERE c1 = ALL(ARRAY[$1, $2, $3]);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p10(1, 2, 3);

PREPARE p11(INT, INT, INT) AS SELECT * FROM t1 WHERE c1 = ANY(ARRAY[$1, $2, $3]);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p11(1, 2, 3);

PREPARE p12(INT, INT, INT) AS SELECT * FROM t1 WHERE c1 = SOME(ARRAY[$1, $2, $3]);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p12(1, 2, 3);

set plan_cache_mode = 'force_generic_plan';

PREPARE p13(TEXT) AS SELECT * FROM t1 WHERE c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p13('12');

PREPARE p14(TEXT) AS SELECT * FROM t1 WHERE c1 = LENGTHB($1);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p14('hello');

PREPARE p15(INT) AS SELECT * FROM t1 WHERE c1 = ALL(SELECT c2 FROM t1 WHERE c1 > $1);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p15(1);

PREPARE p16(name) AS SELECT * FROM t1 WHERE c1 = $1;

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p16('12');

create sequence seq;

PREPARE p17(TEXT) AS SELECT * FROM t1 WHERE c1 = currval($1);

EXPLAIN (VERBOSE ON, COSTS OFF) EXECUTE p17('seq');

